version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./tacy_app
    command: gunicorn tacy_app.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: dev_db
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  frontend:
    restart: unless-stopped
    build:
      context: ./react

    volumes:
      - react_build:/react/build
    ports:
      - "80:80"

volumes:
  react_build:

    # sudo docker-compose -f docker-compose.yml build


