version: "3"

services:
  backend:
    container_name: tacy_backend_container
    # command: "gunicorn tacy_app.tacy_app:application --bind 0.0.0.0:8000"
    build:
      context: ./tacy_app
    restart: always
    volumes:
      - .:/tacy_app
      - ./tacy_app/tacy_app/media:/tacy_app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./tacy_app/.env
    expose:
      - 8000

  db:
    container_name: "tacy_backend_postgres_container"
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "tacy_project_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./tacy_app/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=z@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=z
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
    ports:
      - "5555:5555"
  frontend:
    restart: unless-stopped
    build:
      context: ./react

    volumes:
      - react_build:/react/build
    ports:
      - "80:80"

volumes:
  react_build:

    # sudo docker-compose -f docker-compose.yml build


