version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./tacy_app
    command: gunicorn tacy_app.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    restart: unless-stopped
    build:
      context: ./react
    command: npm start
    volumes:
      - react_build:/react/build

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react_build:


