FROM node:16.15.1 as builder
WORKDIR /react
COPY package.json /react/
RUN npm install
COPY . /react
EXPOSE 3000
RUN npm run build
CMD ["npm", "start"]

# FROM nginx:alpine

# #!/bin/sh

# COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

# ## Remove default nginx index page
# RUN rm -rf /usr/share/nginx/html/*

# # Copy from the stahg 1
# COPY --from=builder /react/build /usr/share/nginx/html

# EXPOSE 3000 80

# ENTRYPOINT ["nginx", "-g", "daemon off;"]