# Generated by Django 4.1.2 on 2022-11-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0062_rename_iniative_active_metricsproject_initiative_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_initiatives', to='projects.project')),
            ],
        ),
    ]
