# Generated by Django 4.1.5 on 2023-01-27 10:59

import components.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название мероприятия', max_length=500, verbose_name='Название мероприятия')),
                ('date_start', models.DateField(help_text='Введите дату начала мероприятия', verbose_name='Дата начала мероприятия')),
                ('date_end', models.DateField(help_text='Введите дату окончания мероприятия', verbose_name='Дата окончания мероприятия')),
                ('ready', models.BooleanField(default=False, verbose_name='Отметка об выполнении')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название инициативы', max_length=500, verbose_name='Название инициативы')),
                ('current_state', models.CharField(help_text='Введите текущее состояние инициативы', max_length=500, verbose_name='Текущее состояние инициативы')),
                ('reasons', models.CharField(help_text='Введите предпосылкт инициативы', max_length=500, verbose_name='Предпосылки инициативы')),
                ('description', models.CharField(help_text='Введите описание инициативы', max_length=500, verbose_name='Описание инициативы')),
                ('date_registration', models.DateField(default=django.utils.timezone.now, help_text='Введите дату регистрации инициативы', verbose_name='Дата регистраци инициативы')),
                ('date_start', models.DateField(default=django.utils.timezone.now, help_text='Введите дату начала инициативы', verbose_name='min(date start events)')),
                ('date_end', models.DateField(default=django.utils.timezone.now, help_text='Введите дату окончания инициативы', verbose_name='max(date end events)')),
                ('activate', models.BooleanField(default=False, verbose_name='Флаг Инициатва прошла согласование')),
                ('failure', models.BooleanField(default=False, verbose_name='Флаг Инициативу отозвали')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_initiatives', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся инициативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'db_table': 'initiatives',
            },
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название риска', max_length=200, verbose_name='Название риска')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_risks', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='components.initiatives')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='SettingsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_initiatives', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsStatusInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Вес статуса')),
                ('name', models.CharField(help_text='Введите название статуса', max_length=200, verbose_name='Название статуса')),
                ('settings_project', models.ForeignKey(blank=True, help_text='Проект к которому относятся статусы инициативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_status', to='components.settingscomponents', verbose_name='Проект')),
            ],
            options={
                'db_table': 'settings_status_initiative',
            },
        ),
        migrations.CreateModel(
            name='SettingsFilesInitiative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите название файла', max_length=200, verbose_name='Название файла')),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_files', to='components.settingscomponents')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_files', to='components.settingsstatusinitiative')),
            ],
            options={
                'db_table': 'project_settings_files',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsRisks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=200)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_risk_add_fields',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=30)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_initiative_add_fields',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=200)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_event_add_fields',
            },
        ),
        migrations.CreateModel(
            name='RolesUserInInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='components.initiatives')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rolesproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RisksAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.risks')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsrisks')),
            ],
            options={
                'db_table': 'risk_add_fields',
            },
        ),
        migrations.CreateModel(
            name='InitiativesPropertiesFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_fields', to='components.initiatives')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject')),
                ('values', models.ManyToManyField(to='projects.propertiesitemsproject')),
            ],
            options={
                'db_table': 'initiatives_properties_fields',
            },
        ),
        migrations.CreateModel(
            name='InitiativesMetricsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=200)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_fields', to='components.initiatives')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject')),
            ],
            options={
                'db_table': 'initiatives_metric_fields',
            },
        ),
        migrations.CreateModel(
            name='InitiativesFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=components.models.directory_path)),
                ('file_name', models.CharField(max_length=300)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='components.initiatives')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.settingsfilesinitiative')),
            ],
            options={
                'db_table': 'initiatives_files',
            },
        ),
        migrations.CreateModel(
            name='InitiativesAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.initiatives')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsinitiative')),
            ],
            options={
                'db_table': 'initiatives_add_fields',
            },
        ),
        migrations.AddField(
            model_name='initiatives',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='components.settingsstatusinitiative'),
        ),
        migrations.CreateModel(
            name='EventsAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.events')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsevent')),
            ],
            options={
                'db_table': 'event_add_fields',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='components.initiatives'),
        ),
        migrations.CreateModel(
            name='EventMetricsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=500)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_fields', to='components.events')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject')),
            ],
            options={
                'db_table': 'event_metrics_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='settingsstatusinitiative',
            constraint=models.UniqueConstraint(fields=('settings_project', 'name'), name='unique status name initiatives'),
        ),
        migrations.AddConstraint(
            model_name='risksaddfields',
            constraint=models.UniqueConstraint(fields=('risk', 'title'), name='unique field risk title'),
        ),
        migrations.AddConstraint(
            model_name='risks',
            constraint=models.UniqueConstraint(fields=('initiative', 'name'), name='unique field risk name'),
        ),
        migrations.AddConstraint(
            model_name='initiativesmetricsfields',
            constraint=models.UniqueConstraint(fields=('initiative', 'metric'), name='unique field metric title'),
        ),
        migrations.AddConstraint(
            model_name='initiativesfiles',
            constraint=models.UniqueConstraint(fields=('initiative', 'title'), name='unique field initiative title'),
        ),
        migrations.AddConstraint(
            model_name='initiativesaddfields',
            constraint=models.UniqueConstraint(fields=('initiative', 'title'), name='unique field initiatives title'),
        ),
        migrations.AddConstraint(
            model_name='initiatives',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique name initiatives'),
        ),
        migrations.AddConstraint(
            model_name='eventsaddfields',
            constraint=models.UniqueConstraint(fields=('event', 'title'), name='unique field event title'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('initiative', 'name'), name='unique event initiative name'),
        ),
        migrations.AddConstraint(
            model_name='eventmetricsfields',
            constraint=models.UniqueConstraint(fields=('event', 'metric'), name='unique event field metric title'),
        ),
    ]
