# Generated by Django 4.1.2 on 2022-11-09 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0062_rename_iniative_active_metricsproject_initiative_activate'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название инициативы', max_length=30, verbose_name='Название инициативы')),
                ('curent_state', models.CharField(help_text='Введите текущее состояние инициативы', max_length=150, verbose_name='Текущее состояние инициативы')),
                ('reasons', models.CharField(help_text='Введите предпосылкт инициативы', max_length=150, verbose_name='Предпосылки инициативы')),
                ('description', models.CharField(help_text='Введите описание инициативы', max_length=150, verbose_name='Описание инициативы')),
                ('date_start', models.DateField(help_text='Введите дату начала инициативы', verbose_name='Дата начала инициативы')),
                ('date_end', models.DateField(help_text='Введите дату окончания инициативы', verbose_name='Дата окончания инициативы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_initiatives', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся инициативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'db_table': 'initiatives',
            },
        ),
        migrations.AddConstraint(
            model_name='initiatives',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique name initiatives'),
        ),
    ]
