# Generated by Django 4.1.2 on 2023-01-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingscomponents',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_initiatives', to='projects.project'),
        ),
        migrations.AddField(
            model_name='settingsaddfeldsrisks',
            name='settings_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks_addfields', to='components.settingscomponents'),
        ),
        migrations.AddField(
            model_name='settingsaddfeldsinitiative',
            name='settings_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_addfields', to='components.settingscomponents'),
        ),
        migrations.AddField(
            model_name='settingsaddfeldsevent',
            name='settings_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_addfields', to='components.settingscomponents'),
        ),
        migrations.AddField(
            model_name='rolesuserininitiative',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='components.initiatives'),
        ),
        migrations.AddField(
            model_name='rolesuserininitiative',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rolesproject'),
        ),
    ]
