# Generated by Django 4.1.5 on 2023-01-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_initiatives_unique name initiatives'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='risks',
            name='unique field risk name',
        ),
    ]
