# Generated by Django 4.1.2 on 2022-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initiatives_initiatives_unique name initiatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название мероприятия', max_length=30, unique=True, verbose_name='Название мероприятия')),
                ('date_start', models.DateField(help_text='Введите дату начала мероприятия', verbose_name='Дата начала мероприятия')),
                ('date_end', models.DateField(help_text='Введите дату окончания мероприятия', verbose_name='Дата окончания мероприятия')),
            ],
        ),
    ]
