# Generated by Django 4.1.2 on 2022-12-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_risks', to=settings.AUTH_USER_MODEL),
        ),
    ]
