# Generated by Django 4.1.5 on 2023-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_remove_risks_unique field risk name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatives',
            name='current_state',
            field=models.CharField(blank=True, help_text='Введите текущее состояние инициативы', max_length=500, null=True, verbose_name='Текущее состояние инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание инициативы', max_length=500, null=True, verbose_name='Описание инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='reasons',
            field=models.CharField(blank=True, help_text='Введите предпосылкт инициативы', max_length=500, null=True, verbose_name='Предпосылки инициативы'),
        ),
        migrations.AlterField(
            model_name='initiativesaddfields',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
