# Generated by Django 4.1.2 on 2022-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название риска', max_length=30, unique=True, verbose_name='Название риска')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
    ]
