# Generated by Django 4.1.2 on 2022-11-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_risks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsStatusInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Вес статуса')),
                ('name', models.CharField(help_text='Введите название статуса', max_length=30, verbose_name='Название статуса')),
                ('settings_project', models.ForeignKey(blank=True, help_text='Проект к которому относятся статусы инициативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_status', to='components.settingscomponents', verbose_name='Проект')),
            ],
            options={
                'db_table': 'status_initiative',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsRisks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=30, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=30)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_risk_add_fields',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=30, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=30)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_initiative_add_fields',
            },
        ),
        migrations.CreateModel(
            name='SettingsAddFeldsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название инициативы', max_length=30, verbose_name='Название дополнительного поля')),
                ('type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=30)),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_addfields', to='components.settingscomponents')),
            ],
            options={
                'db_table': 'project_settings_event_add_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='settingsstatusinitiative',
            constraint=models.UniqueConstraint(fields=('settings_project', 'name'), name='unique status name initiatives'),
        ),
    ]
