# Generated by Django 4.1.5 on 2023-02-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_initiatives_current_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsstatusinitiative',
            name='settings_project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся статусы инициативы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_status', to='components.settingscomponents', verbose_name='Проект'),
        ),
    ]
