# Generated by Django 4.1.5 on 2023-01-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectfiles_id_and_more'),
        ('components', '0004_remove_initiativespropertiesfields_unique field properties title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativespropertiesfields',
            name='value',
        ),
        migrations.AddField(
            model_name='initiativespropertiesfields',
            name='values',
            field=models.ManyToManyField(to='projects.propertiesitemsproject'),
        ),
    ]
