# Generated by Django 4.1.5 on 2023-02-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_communityaddfields_value'),
        ('components', '0005_alter_settingsstatusinitiative_settings_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingscomponents',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_initiatives', to='projects.project'),
        ),
    ]
