# Generated by Django 4.1.5 on 2023-01-13 22:49

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_initiativespropertiesfields_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsFilesInitiative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите название файла', max_length=200, verbose_name='Название файла')),
                ('settings_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_files', to='components.settingscomponents')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_files', to='components.settingsstatusinitiative')),
            ],
            options={
                'db_table': 'project_settings_files',
            },
        ),
        migrations.CreateModel(
            name='InitiativesFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=components.models.directory_path)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_files', to='components.initiatives')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.settingsfilesinitiative')),
            ],
            options={
                'db_table': 'initiatives_files',
            },
        ),
        migrations.AddConstraint(
            model_name='initiativesfiles',
            constraint=models.UniqueConstraint(fields=('initiative', 'title'), name='unique field initiative title'),
        ),
    ]
