# Generated by Django 4.1.2 on 2022-11-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_settingsstatusinitiative_settingsaddfeldsrisks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativesAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.settingsaddfeldsinitiative')),
            ],
        ),
    ]
