# Generated by Django 4.1.5 on 2023-02-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_communityaddfields_value'),
        ('components', '0006_alter_settingscomponents_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatives',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='components.settingsstatusinitiative'),
        ),
        migrations.AlterField(
            model_name='settingscomponents',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_initiatives', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='settingsstatusinitiative',
            name='settings_project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся статусы инициативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_status', to='components.settingscomponents', verbose_name='Проект'),
        ),
    ]
