# Generated by Django 4.1.5 on 2023-01-14 16:13

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_settingsfilesinitiative_initiativesfiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesfiles',
            name='file',
            field=models.FileField(default=1, upload_to=components.models.directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='initiativesfiles',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='components.initiatives'),
        ),
    ]
