# Generated by Django 4.1.2 on 2022-11-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_initiativesaddfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativesaddfields',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsinitiative'),
        ),
        migrations.AlterField(
            model_name='initiativesaddfields',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.initiatives'),
        ),
    ]
