# Generated by Django 4.1.2 on 2022-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_initiativesaddfields_title_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='initiativesaddfields',
            constraint=models.UniqueConstraint(fields=('initiative', 'title'), name='unique field initiatives title'),
        ),
        migrations.AlterModelTable(
            name='initiativesaddfields',
            table='initiatives_add_fields',
        ),
    ]
