# Generated by Django 4.1.2 on 2022-11-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_initiativesaddfields_unique field initiatives title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='components.initiatives'),
        ),
    ]
