# Generated by Django 4.1.5 on 2023-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_initiatives_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatives',
            name='current_state',
            field=models.CharField(blank=True, help_text='Введите текущее состояние инициативы', max_length=1000, null=True, verbose_name='Текущее состояние инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='reasons',
            field=models.CharField(blank=True, help_text='Введите предпосылкт инициативы', max_length=1000, null=True, verbose_name='Предпосылки инициативы'),
        ),
        migrations.AlterField(
            model_name='initiativesaddfields',
            name='value',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
