# Generated by Django 4.1.2 on 2022-11-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_risks_initiative'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisksAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.risks')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsrisks')),
            ],
            options={
                'db_table': 'risk_add_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='risksaddfields',
            constraint=models.UniqueConstraint(fields=('risk', 'title'), name='unique field risk title'),
        ),
    ]
