# Generated by Django 4.1.2 on 2022-11-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_risksaddfields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='components.events')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsaddfeldsevent')),
            ],
            options={
                'db_table': 'event_add_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='eventsaddfields',
            constraint=models.UniqueConstraint(fields=('event', 'title'), name='unique field event title'),
        ),
    ]
