# Generated by Django 4.1.2 on 2022-11-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_eventsaddfields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='components.initiatives'),
        ),
    ]
