# Generated by Django 4.1.2 on 2022-11-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_alter_propertiesproject_initiative_activate'),
        ('components', '0012_events_initiative'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativesPropertiesFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_fields', to='components.initiatives')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesitemsproject')),
            ],
            options={
                'db_table': 'initiatives_properties_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='initiativespropertiesfields',
            constraint=models.UniqueConstraint(fields=('initiative', 'title'), name='unique field properties title'),
        ),
    ]
