# Generated by Django 4.1.2 on 2022-11-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_alter_propertiesproject_initiative_activate'),
        ('components', '0013_initiativespropertiesfields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativesMetricsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_fields', to='components.initiatives')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject')),
            ],
            options={
                'db_table': 'initiatives_metric_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='initiativesmetricsfields',
            constraint=models.UniqueConstraint(fields=('initiative', 'metric'), name='unique field metric title'),
        ),
    ]
