# Generated by Django 4.1.2 on 2022-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_initiativesmetricsfields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmetricsfields',
            name='value',
            field=models.FloatField(),
        ),
    ]
