# Generated by Django 4.1.2 on 2022-11-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_alter_propertiesproject_initiative_activate'),
        ('components', '0015_alter_initiativesmetricsfields_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmetricsfields',
            name='value',
            field=models.FloatField(max_length=200),
        ),
        migrations.CreateModel(
            name='EventMetricsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=200)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_fields', to='components.events')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject')),
            ],
            options={
                'db_table': 'initiatives_event_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='eventmetricsfields',
            constraint=models.UniqueConstraint(fields=('event', 'metric'), name='unique event field metric title'),
        ),
    ]
