# Generated by Django 4.1.2 on 2022-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_alter_initiativesmetricsfields_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(help_text='Введите название мероприятия', max_length=30, verbose_name='Название мероприятия'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('initiative', 'name'), name='unique event initiative name'),
        ),
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
