# Generated by Django 4.1.2 on 2022-11-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_alter_events_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventmetricsfields',
            table='event_metrics_fields',
        ),
    ]
