# Generated by Django 4.1.2 on 2022-11-14 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_events_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiatives',
            name='date_registration',
            field=models.DateField(default=django.utils.timezone.now, help_text='Введите дату регистрации инициативы', verbose_name='Дата регистраци инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, help_text='Введите дату окончания инициативы', verbose_name='max(date end events)'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Введите дату начала инициативы', verbose_name='min(date start events)'),
        ),
    ]
