# Generated by Django 4.1.2 on 2022-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_initiatives_date_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Флаг активности'),
        ),
        migrations.AddField(
            model_name='initiatives',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Флаг Инициатва прошла согласование'),
        ),
        migrations.AddField(
            model_name='initiatives',
            name='failure',
            field=models.BooleanField(default=False, verbose_name='Флаг Инициативу отозвали'),
        ),
    ]
