# Generated by Django 4.1.2 on 2022-11-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_initiatives_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiatives',
            name='status',
        ),
    ]
