# Generated by Django 4.1.2 on 2022-11-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_remove_initiatives_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiatives',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='components.settingsstatusinitiative'),
        ),
    ]
