# Generated by Django 4.1.2 on 2022-11-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_initiatives_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiatives',
            old_name='curent_state',
            new_name='current_state',
        ),
    ]
