# Generated by Django 4.1.2 on 2022-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_rename_curent_state_initiatives_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='activate',
        ),
        migrations.AddField(
            model_name='events',
            name='ready',
            field=models.BooleanField(default=True, verbose_name='Отметка об выполнении'),
        ),
    ]
