# Generated by Django 4.1.2 on 2022-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_remove_events_activate_events_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Отметка об выполнении'),
        ),
    ]
