# Generated by Django 4.1.2 on 2022-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_alter_events_ready'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='risks',
            constraint=models.UniqueConstraint(fields=('initiative', 'name'), name='unique field risk name'),
        ),
    ]
