# Generated by Django 4.1.2 on 2022-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0028_risks_unique field risk name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatives',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Флаг Инициатва прошла согласование'),
        ),
    ]
