# Generated by Django 4.1.2 on 2022-11-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_alter_initiatives_activate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settingsstatusinitiative',
            table='settings_status_initiative',
        ),
    ]
