# Generated by Django 4.1.2 on 2022-11-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0030_alter_settingsstatusinitiative_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsaddfields',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
