# Generated by Django 4.1.2 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0031_alter_eventsaddfields_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmetricsfields',
            name='value',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(help_text='Введите название мероприятия', max_length=500, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventsaddfields',
            name='value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='current_state',
            field=models.CharField(help_text='Введите текущее состояние инициативы', max_length=500, verbose_name='Текущее состояние инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='description',
            field=models.CharField(help_text='Введите описание инициативы', max_length=500, verbose_name='Описание инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='name',
            field=models.CharField(help_text='Введите название инициативы', max_length=500, verbose_name='Название инициативы'),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='reasons',
            field=models.CharField(help_text='Введите предпосылкт инициативы', max_length=500, verbose_name='Предпосылки инициативы'),
        ),
        migrations.AlterField(
            model_name='risks',
            name='name',
            field=models.CharField(help_text='Введите название риска', max_length=200, unique=True, verbose_name='Название риска'),
        ),
        migrations.AlterField(
            model_name='risksaddfields',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='settingsaddfeldsevent',
            name='title',
            field=models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля'),
        ),
        migrations.AlterField(
            model_name='settingsaddfeldsevent',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=200),
        ),
        migrations.AlterField(
            model_name='settingsaddfeldsinitiative',
            name='title',
            field=models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля'),
        ),
        migrations.AlterField(
            model_name='settingsaddfeldsrisks',
            name='title',
            field=models.CharField(help_text='Введите название инициативы', max_length=200, verbose_name='Название дополнительного поля'),
        ),
        migrations.AlterField(
            model_name='settingsaddfeldsrisks',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('date', 'date')], default='str', max_length=200),
        ),
        migrations.AlterField(
            model_name='settingsstatusinitiative',
            name='name',
            field=models.CharField(help_text='Введите название статуса', max_length=200, verbose_name='Название статуса'),
        ),
    ]
