# Generated by Django 4.1.2 on 2022-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0032_alter_eventmetricsfields_value_alter_events_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risks',
            name='name',
            field=models.CharField(help_text='Введите название риска', max_length=200, verbose_name='Название риска'),
        ),
    ]
