# Generated by Django 4.1.2 on 2022-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0033_alter_risks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksaddfields',
            name='value',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
