# Generated by Django 4.1.2 on 2022-11-27 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0003_initial'),
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagescoordinationinitiative',
            name='coordinator_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagescoordinationinitiative',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages_coordination', to='components.initiatives'),
        ),
        migrations.AddField(
            model_name='stagescoordinationinitiative',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.settingsstatusinitiative'),
        ),
        migrations.AddField(
            model_name='coordinationinitiativehistory',
            name='author_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinationinitiativehistory',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinationinitiativehistory',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_coordination', to='components.initiatives'),
        ),
        migrations.AddField(
            model_name='coordinationinitiativehistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsstatusinitiative'),
        ),
        migrations.AddConstraint(
            model_name='stagescoordinationinitiative',
            constraint=models.UniqueConstraint(fields=('initiative', 'status', 'coordinator_stage'), name='unique status coordinator_stage'),
        ),
    ]
