# Generated by Django 4.1.5 on 2023-02-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_unique name project'),
        ('coordination', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagescoordinationinitiative',
            name='coordinator_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.rolesproject'),
        ),
    ]
