# Generated by Django 4.1.2 on 2022-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_coordinationinitiativehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='action',
            field=models.CharField(choices=[('Отправить на согласование', 'Отправить на согласование'), ('Left a comment', 'Left a comment'), ('Agreed', 'Agreed'), ('Withdrew the initiative', 'Withdrew the initiative')], max_length=30),
        ),
    ]
