# Generated by Django 4.1.2 on 2023-01-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagescoordinationinitiative',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
