# Generated by Django 4.1.2 on 2022-11-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_alter_coordinationinitiativehistory_action'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stagescoordinationinitiative',
            constraint=models.UniqueConstraint(fields=('status', 'coordinator_stage'), name='unique status coordinator_stage'),
        ),
    ]
