# Generated by Django 4.1.2 on 2022-11-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0004_stagescoordinationinitiative_unique status coordinator_stage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coordinationinitiativehistory',
            constraint=models.UniqueConstraint(fields=('status', 'coordinator'), name='unique status coordinator'),
        ),
    ]
