# Generated by Django 4.1.2 on 2022-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0005_coordinationinitiativehistory_unique status coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagescoordinationinitiative',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
