# Generated by Django 4.1.2 on 2022-11-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0006_stagescoordinationinitiative_activate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinationinitiativehistory',
            name='unique status coordinator',
        ),
    ]
