# Generated by Django 4.1.2 on 2022-11-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordination', '0007_remove_coordinationinitiativehistory_unique status coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='action',
            field=models.CharField(choices=[('Отправить на согласование', 'Отправить на согласование'), ('Новый комментарий', 'Новый комментарий'), ('Agreed', 'Agreed'), ('Withdrew the initiative', 'Withdrew the initiative')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
