# Generated by Django 4.1.2 on 2022-11-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_initiatives_status'),
        ('coordination', '0009_alter_coordinationinitiativehistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.settingsstatusinitiative'),
        ),
    ]
