# Generated by Django 4.1.2 on 2022-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0010_alter_coordinationinitiativehistory_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stagescoordinationinitiative',
            name='unique status coordinator_stage',
        ),
        migrations.AddConstraint(
            model_name='stagescoordinationinitiative',
            constraint=models.UniqueConstraint(fields=('initiative', 'status', 'coordinator_stage'), name='unique status coordinator_stage'),
        ),
    ]
