# Generated by Django 4.1.2 on 2022-11-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0011_remove_stagescoordinationinitiative_unique status coordinator_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinationinitiativehistory',
            options={'ordering': ['date']},
        ),
    ]
