# Generated by Django 4.1.2 on 2022-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0012_alter_coordinationinitiativehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='action',
            field=models.CharField(choices=[('Отправить на согласование', 'Отправить на согласование'), ('Новый комментарий', 'Новый комментарий'), ('Инициатива согласована', 'Инициатива согласована'), ('Служебное сообщение', 'Служебное сообщение'), ('Инициатива отозвана', 'Инициатива отозвана')], max_length=30),
        ),
    ]
