# Generated by Django 4.1.2 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0013_alter_coordinationinitiativehistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationinitiativehistory',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
