# Generated by Django 4.1.2 on 2022-10-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_author'),
        ('users', '0002_remove_user_phone_number_remove_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_active', to='projects.project'),
        ),
    ]
