# Generated by Django 4.1.2 on 2022-11-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0069_delete_graficsproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.ManyToManyField(to='projects.metricsproject')),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся графики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafics', to='projects.project', verbose_name='Проект')),
                ('propertie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject')),
            ],
            options={
                'db_table': 'grafics_project',
            },
        ),
    ]
