# Generated by Django 4.1.2 on 2022-11-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('grafics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficsproject',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject'),
        ),
        migrations.AddField(
            model_name='graficsproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся графики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafics', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='graficsproject',
            name='propertie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject'),
        ),
    ]
