# Generated by Django 4.1.5 on 2023-02-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_alter_initiatives_status_and_more'),
        ('projects', '0005_alter_communityaddfields_value'),
        ('grafics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGraficsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.settingsstatusinitiative')),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся графики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_grafics', to='projects.project', verbose_name='Проект')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject')),
            ],
        ),
    ]
