# Generated by Django 4.1.5 on 2023-02-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_alter_initiatives_status_and_more'),
        ('projects', '0005_alter_communityaddfields_value'),
        ('grafics', '0002_statusgraficsproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusgraficsproject',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject'),
        ),
        migrations.AlterField(
            model_name='statusgraficsproject',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.settingsstatusinitiative'),
        ),
    ]
