# Generated by Django 4.1.2 on 2022-11-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_delete_graficsproject'),
        ('grafics', '0002_rename_propertie_graficsproject_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graficsproject',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='graficsproject',
            name='properties',
        ),
        migrations.AddField(
            model_name='graficsproject',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graficsproject',
            name='properties',
            field=models.ManyToManyField(to='projects.propertiesproject'),
        ),
    ]
