# Generated by Django 4.1.5 on 2023-02-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafics', '0003_alter_statusgraficsproject_metric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusgraficsproject',
            name='status',
        ),
        migrations.AlterModelTable(
            name='statusgraficsproject',
            table='grafics_status_project',
        ),
    ]
