# Generated by Django 4.1.2 on 2022-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafics', '0004_remove_graficsproject_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficsproject',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
