# Generated by Django 4.1.2 on 2022-11-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_rightsuserbool_is_watch'),
        ('grafics', '0005_graficsproject_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graficsproject',
            name='metrics',
        ),
        migrations.AddField(
            model_name='graficsproject',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.metricsproject'),
            preserve_default=False,
        ),
    ]
