FROM python:3.8.10
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /tacy_app
COPY requirements.txt /tacy_app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /tacy_app/
EXPOSE 8000
ENV PYTHONPATH "${PYTHONPATH}:/tacy_app"

