# Generated by Django 4.1.2 on 2022-10-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название проекта', max_length=30, verbose_name='Название проекта')),
                ('date_start', models.DateField(help_text='Дата начала')),
                ('date_end', models.DateField(help_text='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='MetricsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('values', models.FloatField()),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateDateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся промежуточные даты', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_dates', to='projects.project', verbose_name='Проект')),
            ],
        ),
    ]
