# Generated by Django 4.1.5 on 2023-01-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='сommunityproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolesproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся права пользователей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Свойства пользователя в комманде', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.сommunityproject', verbose_name='Свойства пользователя'),
        ),
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject'),
        ),
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='values',
            field=models.ManyToManyField(to='projects.propertiesitemsproject'),
        ),
        migrations.AddField(
            model_name='propertiesproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся свойства', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='propertiesitemsproject',
            name='propertie',
            field=models.ForeignKey(blank=True, help_text='Введите название свойтсва', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.propertiesproject', verbose_name='Значение свойства'),
        ),
        migrations.AddField(
            model_name='projectstages',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.ManyToManyField(related_name='projects', through='projects.СommunityProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metricsproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='intermediatedateproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся промежуточные даты', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_dates', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='communitysettingsaddfields',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_settings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='communityaddfields',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='projects.сommunityproject'),
        ),
        migrations.AddField(
            model_name='communityaddfields',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.communitysettingsaddfields'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('id', 'name'), name='unique name project'),
        ),
    ]
