# Generated by Django 4.1.2 on 2022-10-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='intermediatedateproject',
            table='intermediate_dates',
        ),
        migrations.AlterModelTable(
            name='metricsproject',
            table='metrics',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
