# Generated by Django 4.1.2 on 2023-01-04 12:37

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, upload_to=projects.models.directory_path),
        ),
    ]
