# Generated by Django 4.1.5 on 2023-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityaddfields',
            name='value',
            field=models.CharField(default='', max_length=500),
        ),
    ]
