# Generated by Django 4.1.2 on 2022-10-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_intermediatedateproject_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название свойства', max_length=30, verbose_name='Название свойства')),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся свойства', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesItemsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=30)),
                ('project', models.ForeignKey(blank=True, help_text='Возможные варианты значений свойтсв', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_items', to='projects.propertiesproject', verbose_name='Значение свойства')),
            ],
        ),
    ]
