# Generated by Django 4.1.5 on 2023-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_communityaddfields_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesitemsproject',
            name='value_short',
            field=models.CharField(blank=True, default='', help_text='Сокращение для графиков', max_length=10, verbose_name='Сокращение значения свойства'),
        ),
    ]
