# Generated by Django 4.1.2 on 2022-10-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_propertiesproject_propertiesitemsproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertiesitemsproject',
            old_name='values',
            new_name='value',
        ),
        migrations.AlterModelTable(
            name='propertiesitemsproject',
            table='properties item',
        ),
        migrations.AlterModelTable(
            name='propertiesproject',
            table='properties',
        ),
    ]
