# Generated by Django 4.1.2 on 2023-01-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
    ]
