# Generated by Django 4.1.5 on 2023-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_propertiesitemsproject_value_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityaddfields',
            name='value',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
