# Generated by Django 4.1.2 on 2023-01-07 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='сommunityproject',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания проекта'),
        ),
        migrations.AddField(
            model_name='сommunityproject',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Флаг автора'),
        ),
    ]
