# Generated by Django 4.1.5 on 2023-02-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_communityaddfields_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique name project',
        ),
    ]
