# Generated by Django 4.1.2 on 2022-10-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_propertiesitemsproject_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='intermediatedateproject',
            table='intermediate_dates_tb',
        ),
        migrations.AlterModelTable(
            name='metricsproject',
            table='metrics_tb',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects_tb',
        ),
        migrations.AlterModelTable(
            name='propertiesitemsproject',
            table='properties_item_tb',
        ),
        migrations.AlterModelTable(
            name='propertiesproject',
            table='properties_tb',
        ),
    ]
