# Generated by Django 4.1.2 on 2023-01-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_сommunityproject_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='сommunityproject',
            name='is_create',
            field=models.BooleanField(default=False, help_text='Возможность созданияиния инциативы'),
        ),
    ]
