# Generated by Django 4.1.5 on 2023-01-14 16:13

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectfiles_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='file_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(default=1, upload_to=projects.models.directory_path),
            preserve_default=False,
        ),
    ]
