# Generated by Django 4.1.5 on 2023-02-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_communityaddfields_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityaddfields',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertiesitemsproject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertiesproject',
            options={},
        ),
    ]
