# Generated by Django 4.1.2 on 2022-10-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_сommunityproject_project_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сommunityproject',
            name='param',
        ),
        migrations.AddField(
            model_name='сommunityproject',
            name='rights_user',
            field=models.CharField(default='Просмотр', max_length=30),
        ),
        migrations.AddField(
            model_name='сommunityproject',
            name='role_user',
            field=models.CharField(default='Рабочая групап', max_length=30),
        ),
    ]
