# Generated by Django 4.1.5 on 2023-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_metricsproject_is_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='is_community_activate',
            field=models.BooleanField(default=True, help_text='В сообществе емкость актуальна, например должность'),
        ),
    ]
