# Generated by Django 4.1.5 on 2023-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_propertiesсommunityproject_is_community_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesсommunityproject',
            name='is_community_activate',
        ),
        migrations.AddField(
            model_name='propertiesproject',
            name='is_community_activate',
            field=models.BooleanField(default=True, help_text='В сообществе емкость актуальна, например подразделения'),
        ),
    ]
