# Generated by Django 4.1.5 on 2023-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_propertiesсommunityproject_is_community_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesproject',
            name='is_community_activate',
            field=models.BooleanField(help_text='В сообществе емкость актуальна, например подразделения'),
        ),
    ]
