# Generated by Django 4.1.5 on 2023-01-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_propertiesproject_is_community_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesproject',
            name='initiative_activate',
            field=models.BooleanField(default=True, help_text='Нужно ли выводить метрику в реестре инициатив'),
        ),
        migrations.AlterField(
            model_name='metricsproject',
            name='initiative_activate',
            field=models.BooleanField(default=True, help_text='Нужно ли выводить метрику в реестре инициатив'),
        ),
    ]
