# Generated by Django 4.1.2 on 2022-10-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_metricsnameproject_metricsvaluesproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesitemsproject',
            name='propertie',
            field=models.ForeignKey(blank=True, help_text='Введите название свойтсва', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.propertiesproject', verbose_name='Значение свойства'),
        ),
        migrations.AlterModelTable(
            name='сommunityproject',
            table='community_tb',
        ),
        migrations.CreateModel(
            name='PropertiesСommunityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesproject')),
                ('user', models.ForeignKey(blank=True, help_text='Свойства пользователя в комманде', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_user', to='projects.propertiesсommunityproject', verbose_name='Свойства пользователя')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertiesitemsproject')),
            ],
            options={
                'db_table': 'propert_community_tb',
            },
        ),
    ]
