# Generated by Django 4.1.5 on 2023-01-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rolesproject_initiative_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySettingsAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите навзание доп поля', max_length=200, verbose_name='Название доп поля')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAddFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfields', to='projects.сommunityproject')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.communitysettingsaddfields')),
            ],
        ),
    ]
