# Generated by Django 4.1.2 on 2022-10-14 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_alter_propertiesitemsproject_propertie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сommunityproject',
            name='rights_user',
        ),
        migrations.CreateModel(
            name='RightsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_coordinate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
