# Generated by Django 4.1.5 on 2023-01-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_communitysettingsaddfields_communityaddfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='сommunityproject',
            name='community_activate',
            field=models.BooleanField(default=False, help_text='Флаг отображения в сообществе'),
        ),
    ]
