# Generated by Django 4.1.2 on 2022-10-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_сommunityproject_rights_user_rightsuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rightsuser',
            table='user_rights',
        ),
    ]
