# Generated by Django 4.1.5 on 2023-01-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_сommunityproject_community_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сommunityproject',
            name='community_activate',
        ),
    ]
