# Generated by Django 4.1.5 on 2023-01-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_сommunityproject_community_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesproject',
            name='is_community_activate',
            field=models.BooleanField(default=True, help_text='В сообществе емкость актуальна, например подразделения'),
        ),
    ]
