# Generated by Django 4.1.5 on 2023-01-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_propertiesproject_is_community_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfiles',
            old_name='project',
            new_name='self',
        ),
    ]
