# Generated by Django 4.1.5 on 2023-01-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_project_projectfiles_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfiles',
            old_name='self',
            new_name='project',
        ),
    ]
