# Generated by Django 4.1.2 on 2022-10-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_author_rightsuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesUserInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coverage', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся роли', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='Проект')),
            ],
        ),
    ]
