# Generated by Django 4.1.2 on 2022-10-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_rolesuserinproject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolesuserinproject',
            table='roles_project',
        ),
    ]
