# Generated by Django 4.1.2 on 2022-10-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_rolesuserinproject_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsUserBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_coordinate', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_rights_bool_tb',
            },
        ),
        migrations.AlterModelTable(
            name='rolesuserinproject',
            table='roles_project_tb',
        ),
        migrations.CreateModel(
            name='RightsUSerInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rightsuserbool')),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся права пользователей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'db_table': 'rights_project_tb',
            },
        ),
        migrations.AlterField(
            model_name='сommunityproject',
            name='rights_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='projects.rightsuserinproject'),
        ),
        migrations.DeleteModel(
            name='RightsUser',
        ),
    ]
