# Generated by Django 4.1.2 on 2022-10-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_rightsuserbool_alter_rolesuserinproject_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сommunityproject',
            name='rights_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rightsuserinproject'),
        ),
        migrations.AlterField(
            model_name='сommunityproject',
            name='role_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rolesuserinproject'),
        ),
    ]
