# Generated by Django 4.1.2 on 2022-10-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_сommunityproject_rights_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сommunityproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_info', to='projects.project'),
        ),
    ]
