# Generated by Django 4.1.2 on 2022-10-15 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0024_alter_сommunityproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='community',
            field=models.ManyToManyField(related_name='projects', through='projects.СommunityProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='сommunityproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
