# Generated by Django 4.1.2 on 2022-10-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_description_project_purpose_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesсommunityproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='propertiesсommunityproject',
            name='user',
        ),
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Свойства пользователя в комманде', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.сommunityproject', verbose_name='Свойства пользователя'),
        ),
    ]
