# Generated by Django 4.1.2 on 2022-10-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_propertiesсommunityproject_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsvaluesproject',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metricsvaluesproject',
            name='title',
            field=models.ForeignKey(blank=True, help_text='Введите название метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='projects.metricsnameproject', verbose_name='Название метрики'),
        ),
    ]
