# Generated by Django 4.1.2 on 2022-10-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_metricsvaluesproject_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricsvaluesproject',
            old_name='values',
            new_name='value',
        ),
    ]
