# Generated by Django 4.1.2 on 2022-10-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_rename_values_metricsvaluesproject_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsvaluesproject',
            name='title',
            field=models.ForeignKey(blank=True, help_text='Введите название метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.metricsnameproject', verbose_name='Название метрики'),
        ),
    ]
