# Generated by Django 4.1.2 on 2022-10-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_metricsvaluesproject_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsvaluesproject',
            name='metric',
            field=models.OneToOneField(blank=True, help_text='Введите название метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_value', to='projects.metricsnameproject', verbose_name='Значение метрики'),
        ),
        migrations.AlterField(
            model_name='metricsvaluesproject',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
