# Generated by Django 4.1.2 on 2022-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_metricsvaluesproject_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnameproject',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='MetricsValuesProject',
        ),
    ]
