# Generated by Django 4.1.2 on 2022-10-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_metricsnameproject_value_delete_metricsvaluesproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsnameproject',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект к которому относятся метрики', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterModelTable(
            name='intermediatedateproject',
            table='project_intermediate_dates',
        ),
        migrations.AlterModelTable(
            name='metricsnameproject',
            table='project_metrics',
        ),
    ]
