# Generated by Django 4.1.2 on 2022-10-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_metricsnameproject_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetricsNameProject',
            new_name='MetricsProject',
        ),
        migrations.AlterModelTable(
            name='propertiesitemsproject',
            table='properties_item',
        ),
    ]
