# Generated by Django 4.1.2 on 2022-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_rename_metricsnameproject_metricsproject_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertiesproject',
            table='project_properties',
        ),
    ]
