# Generated by Django 4.1.2 on 2022-10-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_propertiesproject_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuserinproject',
            name='flags',
        ),
        migrations.AddField(
            model_name='rightsuserbool',
            name='right_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='projects.rightsuserinproject'),
            preserve_default=False,
        ),
    ]
