# Generated by Django 4.1.2 on 2022-10-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_rightsuserinproject_flags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuserbool',
            name='right_user',
        ),
        migrations.AddField(
            model_name='rightsuserinproject',
            name='flags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='projects.rightsuserbool'),
            preserve_default=False,
        ),
    ]
