# Generated by Django 4.1.2 on 2022-10-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_rightsuserbool_right_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuserinproject',
            name='flags',
        ),
        migrations.DeleteModel(
            name='RightsUserBool',
        ),
    ]
