# Generated by Django 4.1.2 on 2022-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_remove_rightsuserinproject_flags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsUserBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_coordinate', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_rights_bool_tb',
            },
        ),
    ]
