# Generated by Django 4.1.2 on 2022-10-24 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_rightsuserbool'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightsuserbool',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
