# Generated by Django 4.1.2 on 2022-10-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_rightsuserbool_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuserbool',
            name='project',
        ),
    ]
