# Generated by Django 4.1.2 on 2022-10-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_rightsuserbool_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightsuserbool',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rightsuserinproject',
            name='flags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.rightsuserbool'),
            preserve_default=False,
        ),
    ]
