# Generated by Django 4.1.2 on 2022-10-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_rightsuserbool_project_rightsuserinproject_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stage', models.CharField(max_length=50)),
                ('date_start', models.DateField(help_text='Введите дату начала этапа', verbose_name='Дата начала этапа')),
                ('date_end', models.DateField(help_text='Введите дату конца этапа', verbose_name='Дата конца этапа')),
                ('project', models.ForeignKey(blank=True, help_text='Проект к которому относятся права пользователей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
            ],
        ),
    ]
