# Generated by Django 4.1.2 on 2022-10-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_projectstages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectstages',
            table='stages_project',
        ),
    ]
