# Generated by Django 4.1.2 on 2022-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_alter_projectstages_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
    ]
