# Generated by Django 4.1.2 on 2022-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_remove_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введите название проекта', max_length=30, unique=True, verbose_name='Название проекта'),
        ),
    ]
