# Generated by Django 4.1.2 on 2022-10-26 15:55

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(null=True, upload_to=projects.models.directory_path),
        ),
    ]
