# Generated by Django 4.1.2 on 2022-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_rename_projectgrafics_graficsproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsproject',
            name='target_value',
            field=models.FloatField(default=0, help_text='Введите целевой эффект', verbose_name='Значение метрики, которон мы ждем от итога проекта'),
        ),
        migrations.AlterField(
            model_name='metricsproject',
            name='value',
            field=models.FloatField(default=0, help_text='Введите текущий эффект', verbose_name='Значение метрики, текущее у проекта'),
        ),
    ]
