# Generated by Django 4.1.2 on 2022-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_metricsproject_target_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsproject',
            name='units',
            field=models.CharField(default='рубли', help_text='Введите единицы измерения метрики', max_length=30, verbose_name='Единицы измерения метрики'),
        ),
    ]
