# Generated by Django 4.1.2 on 2022-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_metricsproject_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsproject',
            name='units',
            field=models.CharField(help_text='Введите единицы измерения метрики', max_length=30, verbose_name='Единицы измерения метрики'),
        ),
    ]
