# Generated by Django 4.1.2 on 2022-10-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_alter_metricsproject_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsproject',
            name='target_value',
            field=models.FloatField(help_text='Введите целевой эффект', verbose_name='Значение метрики, которон мы ждем от итога проекта'),
        ),
    ]
