# Generated by Django 4.1.2 on 2022-11-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_alter_project_author_alter_project_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('id', 'name'), name='unique name project'),
        ),
    ]
