# Generated by Django 4.1.2 on 2022-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_project_unique name project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сommunityproject',
            name='rights_user',
        ),
        migrations.AddField(
            model_name='сommunityproject',
            name='rights_user',
            field=models.ManyToManyField(to='projects.rightsuserinproject'),
        ),
    ]
