# Generated by Django 4.1.2 on 2022-11-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_remove_сommunityproject_rights_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstages',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект'),
        ),
    ]
