# Generated by Django 4.1.2 on 2022-11-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_alter_projectstages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsproject',
            name='iziative_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
