# Generated by Django 4.1.2 on 2022-11-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_metricsproject_iziative_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricsproject',
            old_name='iziative_active',
            new_name='iniative_active',
        ),
    ]
