# Generated by Django 4.1.2 on 2022-11-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_rename_iziative_active_metricsproject_iniative_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesproject',
            name='initiative_activate',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
