# Generated by Django 4.1.2 on 2022-11-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_propertiesproject_initiative_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricsproject',
            old_name='iniative_active',
            new_name='initiative_activate',
        ),
    ]
