# Generated by Django 4.1.2 on 2022-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_rename_iniative_active_metricsproject_initiative_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesсommunityproject',
            name='value',
        ),
        migrations.AddField(
            model_name='propertiesсommunityproject',
            name='value',
            field=models.ManyToManyField(to='projects.propertiesitemsproject'),
        ),
    ]
