# Generated by Django 4.1.2 on 2022-11-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_remove_propertiesсommunityproject_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertiesсommunityproject',
            old_name='value',
            new_name='values',
        ),
    ]
