# Generated by Django 4.1.2 on 2022-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_rename_value_propertiesсommunityproject_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsproject',
            name='initiative_activate',
            field=models.BooleanField(default=True),
        ),
    ]
