# Generated by Django 4.1.2 on 2022-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введите название проекта', max_length=30, verbose_name='Название проекта'),
        ),
    ]
