# Generated by Django 4.1.2 on 2022-11-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_alter_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficsProject',
        ),
    ]
