# Generated by Django 4.1.2 on 2022-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_delete_graficsproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightsuserbool',
            name='is_watch',
            field=models.BooleanField(default=False),
        ),
    ]
