# Generated by Django 4.1.2 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatedateproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='metricsproject',
            name='title',
            field=models.CharField(help_text='Введите название метрики', max_length=200, verbose_name='Метрика проекта'),
        ),
        migrations.AlterField(
            model_name='metricsproject',
            name='units',
            field=models.CharField(help_text='Введите единицы измерения метрики', max_length=200, verbose_name='Единицы измерения метрики'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введите название проекта', max_length=300, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projectstages',
            name='name_stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertiesitemsproject',
            name='value',
            field=models.CharField(help_text='Введите возможное значение свойства', max_length=200, verbose_name='Значение свойства'),
        ),
        migrations.AlterField(
            model_name='propertiesproject',
            name='title',
            field=models.CharField(help_text='Введите название свойства', max_length=200, verbose_name='Название свойства'),
        ),
        migrations.AlterField(
            model_name='rightsuserinproject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rolesuserinproject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
