# Generated by Django 4.1.2 on 2022-11-27 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дати время новости', verbose_name='Дата и время новости')),
                ('text', models.CharField(max_length=800)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
