# Generated by Django 4.1.2 on 2022-11-18 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationsuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дати время новости', verbose_name='Дата и время новости'),
        ),
    ]
