# Generated by Django 4.1.2 on 2022-11-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationsuser_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsuser',
            options={'ordering': ['-date']},
        ),
    ]
