# Generated by Django 4.1.2 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationsuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsuser',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
